---
# Extension Auto-Setup: packages

# TimescaleDB (if 'enable_timescale' is 'true')
- name: Install TimescaleDB package
  ansible.builtin.package:
    name: >-
      {% if postgresql_version | int >= 11 %}
      timescaledb-2-postgresql-{{ postgresql_version }}
      {% else %}
      timescaledb-postgresql-{{ postgresql_version }}
      {% endif %}
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  when: (enable_timescale | default(false)| bool) or (enable_timescaledb | default(false)| bool)
  tags: timescaledb, timescale

# pg_repack (if 'enable_pg_repack' is 'true')
- name: Install pg_repack package
  ansible.builtin.package:
    name: >-
      {% if ansible_os_family == 'Debian' %}
      postgresql-{{ postgresql_version }}-repack
      {% else %}
      pg_repack_{{ postgresql_version }}
      {% endif %}
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  when: enable_pg_repack | default(false)| bool
  tags: pg_repack

# pg_cron (if 'enable_pg_cron' is 'true')
- name: Install pg_cron package
  ansible.builtin.package:
    name: >-
      {% if ansible_os_family == 'Debian' %}
      postgresql-{{ postgresql_version }}-cron
      {% else %}
      pg_cron_{{ postgresql_version }}
      {% endif %}
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  when: enable_pg_cron | default(false)| bool
  tags: pg_cron

...
