# yamllint disable rule:line-length
---

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers

# Get info
- name: Get Postgres users
  run_once: true
  become: true
  become_user: postgres
  ansible.builtin.command:
    "{{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -Xc '\\du'"
  register: users_result
  delegate_to: "{{ groups.master[0] }}"
  changed_when: false
  ignore_errors: true
  tags: users, users_list, cluster_info, cluster_status, point_in_time_recovery

- name: Get Postgres databases
  run_once: true
  become: true
  become_user: postgres
  ansible.builtin.command:
    "{{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -Xc '\\l'"
  register: dbs_result
  delegate_to: "{{ groups.master[0] }}"
  changed_when: false
  ignore_errors: true
  tags: databases, db_list, cluster_info, cluster_status, point_in_time_recovery

- name: Get Postgres cluster info
  run_once: true
  become: true
  become_user: postgres
  ansible.builtin.command: patronictl -c /etc/patroni/patroni.yml list
  register: patronictl_result
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
  changed_when: false
  ignore_errors: true
  tags: patroni_status, cluster_info, cluster_status, point_in_time_recovery

# Print info
- name: Postgres list of users
  run_once: true
  ansible.builtin.debug:
    var: users_result.stdout_lines
  when: users_result.stdout_lines is defined
  tags: users, users_list, cluster_info, cluster_status, point_in_time_recovery

- name: Postgres list of databases
  run_once: true
  ansible.builtin.debug:
    var: dbs_result.stdout_lines
  when: dbs_result.stdout_lines is defined
  tags: databases, db_list, cluster_info, cluster_status, point_in_time_recovery

- name: Postgres Cluster info
  run_once: true
  ansible.builtin.debug:
    var: patronictl_result.stdout_lines
  when: patronictl_result.stdout_lines is defined
  tags: patroni_status, cluster_info, cluster_status, point_in_time_recovery

# Connection info
# Note: if the variable 'mask_password' is 'true', do not print the superuser password in connection info.

- block:  # if 'cluster_vip' is defined
    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "address: (VIP) {{ cluster_vip }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "port: {{ haproxy_listen_port.replicas_sync }} (read only) synchronous replica only"
          - "port: {{ haproxy_listen_port.replicas_async }} (read only) asynchronous replicas only"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "address: (VIP) {{ cluster_vip }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and not synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "address: (VIP) {{ cluster_vip }}"
          - "port: {% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: not with_haproxy_load_balancing | bool
  vars:
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
  when:
    - (cluster_vip is defined and cluster_vip | length > 0)
    - dcs_type == "etcd"
    - (cloud_provider | default('') | length < 1 or not cloud_load_balancer | default(false) | bool)
  ignore_errors: true
  tags: conn_info, cluster_info, cluster_status

- block:  # if 'cluster_vip' is not defined and 'pgbouncer_install' is 'true'
    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_haproxy_ip_adresses }}{% endif %}"
          - "private address: {{ haproxy_ip_adresses }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "port: {{ haproxy_listen_port.replicas_sync }} (read only) synchronous replica only"
          - "port: {{ haproxy_listen_port.replicas_async }} (read only) asynchronous replicas only"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_haproxy_ip_adresses }}{% endif %}"
          - "private address: {{ haproxy_ip_adresses }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and not synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_postgres_ip_adresses }}{% endif %}"
          - "private address: {{ postgres_ip_adresses }}"
          - "port: {{ pgbouncer_listen_port }} (pgbouncer)"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: not with_haproxy_load_balancing | bool
  ignore_errors: true
  vars:
    public_haproxy_ip_adresses: "{{ groups['balancers'] | default([]) | map('extract', hostvars, 'ansible_ssh_host') | join(',') }}"
    public_postgres_ip_adresses: "{{ groups['postgres_cluster'] | default([]) | map('extract', hostvars, 'ansible_ssh_host') | join(',') }}"
    haproxy_ip_adresses: "{{ groups['balancers'] | default([]) | map('extract', hostvars, 'inventory_hostname') | join(',') }}"
    postgres_ip_adresses: "{{ groups['postgres_cluster'] | default([]) | map('extract', hostvars, 'inventory_hostname') | join(',') }}"
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
  when:
    - (cluster_vip is not defined or cluster_vip | length < 1)
    - dcs_type == "etcd"
    - pgbouncer_install | bool
    - (cloud_provider | default('') | length < 1 or not cloud_load_balancer | default(false) | bool)
  tags: conn_info, cluster_info, cluster_status

- block:  # if 'cluster_vip' is not defined and 'pgbouncer_install' is 'false'
    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_haproxy_ip_adresses }}{% endif %}"
          - "private address: {{ haproxy_ip_adresses }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "port: {{ haproxy_listen_port.replicas_sync }} (read only) synchronous replica only"
          - "port: {{ haproxy_listen_port.replicas_async }} (read only) asynchronous replicas only"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - ""
          - "connection string (libpq):"
          - "  read-write: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_haproxy_host_port_master }}/postgres' "
          - "  read-only: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_haproxy_host_port_replica }}/postgres' "
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_haproxy_ip_adresses }}{% endif %}"
          - "private address: {{ haproxy_ip_adresses }}"
          - "port: {{ haproxy_listen_port.master }} (read/write) master"
          - "port: {{ haproxy_listen_port.replicas }} (read only) all replicas"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - ""
          - "connection string (libpq):"
          - "  read-write: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_haproxy_host_port_master }}/postgres' "
          - "  read-only: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_haproxy_host_port_replica }}/postgres' "
          - +------------------------------------------------+
      when: with_haproxy_load_balancing | bool and not synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "{% if database_public_access | default(false) | bool %}public address: {{ public_postgres_ip_adresses }}{% endif %}"
          - "private address: {{ postgres_ip_adresses }}"
          - "port: {{ postgresql_port }}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - ""
          - "connection string (libpq):"
          - "  read-write: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_postgres_host_port }}/postgres?target_session_attrs=read-write' "
          - "  read-only: 'postgresql://{{ superuser_username }}:{{ superuser_password }}@{{ libpq_postgres_host_port }}/postgres?target_session_attrs=read-only{{ libpq_load_balance }}' "
          - +------------------------------------------------+
      when: not with_haproxy_load_balancing | bool
  ignore_errors: true
  vars:
    public_haproxy_ip_adresses: "{{ groups['balancers'] | default([]) | map('extract', hostvars, 'ansible_ssh_host') | join(',') }}"
    public_postgres_ip_adresses: "{{ groups['postgres_cluster'] | default([]) | map('extract', hostvars, 'ansible_ssh_host') | join(',') }}"
    haproxy_ip_adresses: "{{ groups['balancers'] | default([]) | map('extract', hostvars, 'inventory_hostname') | join(',') }}"
    postgres_ip_adresses: "{{ groups['postgres_cluster'] | default([]) | map('extract', hostvars, 'inventory_hostname') | join(',') }}"
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
    libpq_haproxy_host_port_master: "{{ haproxy_ip_adresses.split(',') | map('regex_replace', '$', ':' + haproxy_listen_port.master | string) | join(',') }}"
    libpq_haproxy_host_port_replica: "{{ haproxy_ip_adresses.split(',') | map('regex_replace', '$', ':' + haproxy_listen_port.replicas | string) | join(',') }}"
    libpq_postgres_host_port: "{{ postgres_ip_adresses.split(',') | map('regex_replace', '$', ':' + postgresql_port | string) | join(',') }}"
    libpq_load_balance: "{% if postgresql_version is version('16', '>=') %}&load_balance_hosts=random{% endif %}"
  when:
    - (cluster_vip is not defined or cluster_vip | length < 1)
    - dcs_type == "etcd"
    - not pgbouncer_install | bool
    - (cloud_provider | default('') | length < 1 or not cloud_load_balancer | default(false) | bool)
  tags: conn_info, cluster_info, cluster_status

- block:  # if dcs_type: "consul"
    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "Client access point (Consul DNS):"
          - " master.{{ patroni_cluster_name }}.service.consul "
          - " replica.{{ patroni_cluster_name }}.service.consul "
          - "port: {% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: not synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +------------------------------------------------+
          - "Client access point (Consul DNS):"
          - " master.{{ patroni_cluster_name }}.service.consul "
          - " replica.{{ patroni_cluster_name }}.service.consul "
          - " sync-replica.{{ patroni_cluster_name }}.service.consul "
          - " async-replica.{{ patroni_cluster_name }}.service.consul "
          - "port: {% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +------------------------------------------------+
      when: synchronous_mode | bool
  ignore_errors: true
  vars:
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
  when:
    - dcs_type == "consul"
    - (cloud_provider | default('') | length < 1 or not cloud_load_balancer | default(false) | bool)
  tags: conn_info, cluster_info, cluster_status

# Cloud (if 'cloud_provider' is defined)
- block: # AWS
    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +-------------------------------------------------------------------------+
          - "DNS (primary): {{ load_balancer_primary }} "
          - "DNS (replica): {{ load_balancer_replica }} "
          - "port: {% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +-------------------------------------------------------------------------+
      when: not synchronous_mode | bool

    - name: Postgres Cluster connection info
      run_once: true
      ansible.builtin.debug:
        msg:
          - +-------------------------------------------------------------------------+
          - "DNS (primary): {{ load_balancer_primary }} "
          - "DNS (replica): {{ load_balancer_replica }} "
          - "DNS (replica-sync): {{ load_balancer_sync }} "
          - "port: {% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
          - "superuser: {{ superuser_username }}"
          - "password: {{ superuser_password }}"
          - +-------------------------------------------------------------------------+
      when: synchronous_mode | bool
  ignore_errors: true
  vars:
    load_balancer_primary: "{{ (hostvars['localhost']['aws_elb_classic_lb']['results'] | selectattr('item', 'equalto', 'primary') | first).elb.dns_name }}"
    load_balancer_replica: "{{ (hostvars['localhost']['aws_elb_classic_lb']['results'] | selectattr('item', 'equalto', 'replica') | first).elb.dns_name }}"
    load_balancer_sync: "{{ (hostvars['localhost']['aws_elb_classic_lb']['results'] | selectattr('item', 'equalto', 'sync') | first).elb.dns_name }}"
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
  when: cloud_provider | default('') | lower  == 'aws' and cloud_load_balancer | default(false) | bool
  tags: conn_info, cluster_info, cluster_status

# DigitalOcean
- name: Postgres Cluster connection info
  run_once: true
  ansible.builtin.debug:
    msg:
      - +-------------------------------------------------------------------------+
      - "IP Address (primary): {{ load_balancer_primary }} "
      - "IP Address (replica): {{ load_balancer_replica }} {% if synchronous_mode | bool %}(synchronous replica): {{ load_balancer_sync }} {% endif %}"
      - "port: {{ digital_ocean_load_balancer_port | default(database_port) }}"
      - "superuser: {{ superuser_username }}"
      - "password: {{ superuser_password }}"
      - +-------------------------------------------------------------------------+
  ignore_errors: true
  vars:
    load_balancer_primary: "{{ (hostvars['localhost']['digitalocean_load_balancer']['data'] | selectattr('name', 'equalto', patroni_cluster_name + '-primary') | first).ip | default('N/A') }}"
    load_balancer_replica: "{{ (hostvars['localhost']['digitalocean_load_balancer']['data'] | selectattr('name', 'equalto', patroni_cluster_name + '-replica') | first).ip | default('N/A') }}"
    load_balancer_sync: "{{ (hostvars['localhost']['digitalocean_load_balancer']['data'] | selectattr('name', 'equalto', patroni_cluster_name + '-sync') | first).ip | default('N/A') }}"
    database_port: "{% if pgbouncer_install %}{{ pgbouncer_listen_port }} (pgbouncer){% else %}{{ postgresql_port }}{% endif %}"
    superuser_username: "{{ patroni_superuser_username }}"
    superuser_password: "{% if mask_password | default(false) | bool %}'********'{% else %}{{ patroni_superuser_password }}{% endif %}"
  when: cloud_provider | default('') | lower  == 'digitalocean' and cloud_load_balancer | default(false) | bool
  tags: conn_info, cluster_info, cluster_status

...
