---

- block:  # Debian/Ubuntu
    - name: Add repository apt-key
      ansible.builtin.apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ apt_repository_keys }}"
      when: apt_repository_keys | length > 0

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: true
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "Debian"
  tags: add_repo

- block:  # RedHat/CentOS
    - name: Add repository GPG key
      ansible.builtin.command: "rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-{{ ansible_distribution_major_version }}"
      when: ansible_distribution == "AlmaLinux"

    - name: Add repository
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey | default(omit) }}"
        gpgcheck: "{{ item.gpgcheck | default(true) }}"
        enabled: "{{ item.enabled | default(true) }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

    # Install Epel Repository
    - name: Remove epel-release package (if exists)
      ansible.builtin.package:
        name: epel-release
        state: absent
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Get epel-release-latest rpm package
      ansible.builtin.get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Install EPEL repository
      ansible.builtin.package:
        name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    # Install SCL Repository
    - name: Install Software Collections (SCL) repository for CentOS 7
      ansible.builtin.package:
        name: centos-release-scl-rh
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_scl_repo|bool and
            (ansible_distribution == 'CentOS' and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

    - name: Add Software Collections (SCL) repository for OracleLinux 7
      ansible.builtin.yum_repository:
        name: ol7_software_collections
        description: Software Collection Library packages for Oracle Linux 7 (x86_64)
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        gpgcheck: true
        enabled: true
      when: install_scl_repo|bool and
            (ansible_distribution == "OracleLinux" and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

      # Development repository (for llvm-toolset-7-clang)
    - name: Add Development repository for OracleLinux 7
      ansible.builtin.yum_repository:
        name: ol7_developer
        description: Packages for test and development - Oracle Linux 7 (x86_64)
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        gpgcheck: true
        enabled: true
      when: (ansible_distribution == "OracleLinux" and
            ansible_distribution_major_version == '7')

      # Optional Development repository (for libedit-devel)
    - name: Add Optional Development repository for OracleLinux 7
      ansible.builtin.yum_repository:
        name: ol7_optional_developer
        description: Developer preview optional packages for Development on Oracle Linux 7 (x86_64)
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/optional/developer/x86_64
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        gpgcheck: true
        enabled: true
      when: (ansible_distribution == "OracleLinux" and
            ansible_distribution_major_version == '7')

    - name: Enable Software Collections (SCL) repository for RedHat 7
      become: true
      become_user: root
      ansible.builtin.command: subscription-manager repos --enable rhel-server-rhscl-7-rpms
      when: install_scl_repo|bool and
            (ansible_distribution == 'RedHat' and
            ansible_distribution_major_version == '7')
      tags: install_scl_repo

    # Add repository to install dependencies for postgresql<version>-devel package
    - block:
        # PowerTools repository
        - name: Enable PowerTools repository
          ansible.builtin.command: dnf config-manager --set-enabled "[Pp]ower[Tt]ools"
          when:
            - ansible_distribution_major_version is version('8', '==')
            - ansible_distribution != "OracleLinux"
            - ansible_distribution != 'RedHat'

        # CodeReady Linux Builder (crb) repository
        - name: Enable CodeReady Linux Builder (crb) repository
          ansible.builtin.command: dnf config-manager --set-enabled crb
          when:
            - ansible_distribution_major_version is version('9', '>=')
            - ansible_distribution != "OracleLinux"

        # CodeReady Builder repository for OracleLinux
        - name: Enable CodeReady Builder repository
          ansible.builtin.command: dnf config-manager --enable ol{{ ansible_distribution_major_version }}_codeready_builder
          when:
            - ansible_distribution == "OracleLinux"
            - ansible_distribution_major_version is version('8', '>=')
      vars:
        pg_devel_package: "postgresql{{ postgresql_version | replace('.', '') }}-devel"
      when:
        - pg_devel_package in postgresql_packages

    # Install PostgreSQL Repository
    - name: Get pgdg-redhat-repo-latest.noarch.rpm
      ansible.builtin.get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_postgresql_repo|bool
      tags: install_postgresql_repo

    - name: Install PostgreSQL repository
      ansible.builtin.package:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: true
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_postgresql_repo|bool
      tags: install_postgresql_repo

    # Enable Debuginfo repository
    - block:
        - name: Enable PostgreSQL debuginfo repository
          ansible.builtin.shell: |
            set -o pipefail;
            sed -i '/\[pgdg[0-9]*-debuginfo\]/,/^$/ s/enabled=0/enabled=1/' {{ pgdg_redhat_repo_path }}
            sed -i '/\[pgdg[0-9]*-debuginfo\]/,/^$/ s/gpgcheck=1/gpgcheck=0/' {{ pgdg_redhat_repo_path }}
          vars:
            pgdg_redhat_repo_path: "/etc/yum.repos.d/pgdg-redhat-all.repo"

        # Check if the repository entry exists in the file
        - name: Check if pgdg{{ postgresql_version }}-debuginfo exists in repo file
          ansible.builtin.lineinfile:
            path: "{{ pgdg_redhat_repo_path }}"
            regexp: '^\[pgdg{{ postgresql_version }}-debuginfo\]'
            state: absent
          check_mode: true
          changed_when: false
          register: repo_check
          vars:
            pgdg_redhat_repo_path: "/etc/yum.repos.d/pgdg-redhat-all.repo"

        # If the entry does not exist, try to add the repository
        - name: Add pgdg{{ postgresql_version }}-debuginfo repo if not present
          ansible.builtin.yum_repository:
            name: "pgdg{{ postgresql_version }}-debuginfo"
            description: "PostgreSQL {{ postgresql_version }} for RHEL {{ ansible_distribution_major_version }} - x86_64 - Debuginfo"
            baseurl: "https://download.postgresql.org/pub/repos/yum/debug/{{ postgresql_version }}/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64/"
            gpgcheck: false
            enabled: true
          when: repo_check.found == 0
      when: debuginfo_package in postgresql_packages
      vars:
        debuginfo_package: "postgresql{{ postgresql_version }}-debuginfo"
      tags: install_postgresql_repo, debuginfo
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "RedHat"
  tags: add_repo

- name: Extensions repository
  ansible.builtin.import_tasks: extensions.yml
  when: installation_method == "repo"

...
