---

- block:
    - name: Get system username
      become: false
      ansible.builtin.command: whoami
      register: system_user
      changed_when: false

    - name: "Add public keys to ~{{ system_user.stdout }}/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: "{{ system_user.stdout }}"
        key: "{{ item }}"
        state: present
      loop: >
        {% if ssh_public_keys is string %}
          {{ ssh_public_keys.splitlines() }}
        {% else %}
          {{ ssh_public_keys }}
        {% endif %}
  when:
    - ssh_public_keys is defined
    - ssh_public_keys | length > 0
  tags: ssh_public_keys

...
