---
# Dependencies
- name: Install Python dependencies
  block:
    - name: Ensure that 'python3-pip' package is present on controlling host
      ansible.builtin.package:
        name: python3-pip
        state: present
      register: package_status
      until: package_status is success
      delay: 10
      retries: 3
      delegate_to: 127.0.0.1
      run_once: true
      when: ansible_distribution != "MacOSX"

    - name: Ensure that 'boto3' dependency is present on controlling host
      ansible.builtin.pip:
        name: boto3
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true

# SSH key
- block:
    # Delete the temporary ssh key from the cloud (if exists)
    - name: "AWS: Remove temporary SSH key '{{ ssh_key_name }}' from cloud (if any)"
      amazon.aws.ec2_key:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ ssh_key_name }}"
        region: "{{ server_location }}"
        state: absent
      when:
        - ssh_key_name is defined
        - tmp_ssh_key_name is defined
        - ssh_key_name == tmp_ssh_key_name

    # if ssh_key_name and ssh_key_content is specified, add this ssh key to the cloud
    - name: "AWS: Add SSH key '{{ ssh_key_name }}' to cloud"
      amazon.aws.ec2_key:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ ssh_key_name }}"
        key_material: "{{ ssh_key_content }}"
        region: "{{ server_location }}"
        state: present
      register: ssh_key_result
      when:
        - ssh_key_name | length > 0
        - ssh_key_content | length > 0
  when: state == 'present'

# Create (if state is present)
- block:
    # if server_network is specified, get vpc id for this subnet
    - name: "AWS: Gather information about VPC for '{{ server_network }}'"
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ server_location }}"
        subnet_ids: "{{ server_network }}"
      register: vpc_subnet_info
      when: server_network | length > 0

    - name: "Set variable: vpc_id"
      ansible.builtin.set_fact:
        vpc_id: "{{ vpc_subnet_info.subnets[0].vpc_id }}"
      when:
        - server_network | length > 0
        - vpc_subnet_info.subnets[0].vpc_id is defined

    # if server_network is not specified, use default vpc subnet
    - name: "AWS: Gather information about default VPC"
      amazon.aws.ec2_vpc_net_info:
        region: "{{ server_location }}"
        filters:
          "is-default": true
      register: vpc_info
      when: server_network | length < 1

    - name: "AWS: Gather information about VPC subnet for default VPC"
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ server_location }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: vpc_subnet_info
      when:
        - server_network | length < 1
        - vpc_info.vpcs[0].id is defined

    - name: "Set variable: vpc_id"
      ansible.builtin.set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
      when:
        - server_network | length < 1
        - vpc_info.vpcs[0].id is defined

    - name: "Set variable: server_network"
      ansible.builtin.set_fact:
        server_network: "{{ vpc_subnet_info.subnets[0].id }}"
      when:
        - server_network | length < 1
        - vpc_subnet_info.subnets[0].id is defined

    # Security Group (Firewall)
    - name: "AWS: Create or modify Security Group"
      amazon.aws.ec2_security_group:
        name: "{{ patroni_cluster_name }}-security-group"
        state: present
        description: "Security Group for Postgres cluster"
        vpc_id: "{{ vpc_id }}"
        region: "{{ server_location }}"
        rules: "{{ rules }}"
      vars:
        rules: >-
          {{
            ([
              {
                'rule_desc': 'SSH public access',
                'proto': 'tcp',
                'ports': [ansible_ssh_port | default(22)],
                'cidr_ip': ssh_public_allowed_ips | default('0.0.0.0/0', true) | split(',')
              }
            ] if ssh_public_access | bool else []) +
            ([
              {
                'rule_desc': 'Netdata public access',
                'proto': 'tcp',
                'ports': [netdata_port | default('19999')],
                'cidr_ip': netdata_public_allowed_ips | default('0.0.0.0/0', true) | split(',')
              }
            ] if netdata_install | bool and netdata_public_access | bool else []) +
            ([
              {
                'rule_desc': 'Database public access',
                'proto': 'tcp',
                'ports':
                  ([
                    haproxy_listen_port.master | default('5000'),
                    haproxy_listen_port.replicas | default('5001'),
                    haproxy_listen_port.replicas_sync | default('5002'),
                    haproxy_listen_port.replicas_async | default('5003')
                  ] if with_haproxy_load_balancing | bool else []) +
                  ([
                    pgbouncer_listen_port | default('6432')
                  ] if not with_haproxy_load_balancing | bool and pgbouncer_install | bool else []) +
                  ([
                    postgresql_port | default('5432')
                  ] if not with_haproxy_load_balancing | bool and not pgbouncer_install | bool else []),
                'cidr_ip': database_public_allowed_ips | default('0.0.0.0/0', true) | split(',')
              }
            ] if database_public_access | bool else []) +
            [{
              'rule_desc': 'Postgres cluster ports',
              'proto': 'tcp',
              'ports':
                [ansible_ssh_port | default(22)] +
                ([
                  netdata_port | default('19999')
                ] if netdata_install | bool else []) +
                ([
                  pgbouncer_listen_port | default('6432')
                ] if pgbouncer_install | bool else []) +
                [
                  postgresql_port | default('5432'),
                  patroni_restapi_port | default('8008')
                ] +
                ([
                  haproxy_listen_port.master | default('5000'),
                  haproxy_listen_port.replicas | default('5001'),
                  haproxy_listen_port.replicas_sync | default('5002'),
                  haproxy_listen_port.replicas_async | default('5003'),
                  haproxy_listen_port.stats | default('7000')
                ] if with_haproxy_load_balancing | bool else []) +
                ([
                  etcd_client_port | default('2379'),
                  etcd_peer_port | default('2380')
                ] if dcs_type == 'etcd' else []) +
                ([
                  consul_ports_dns | default('8600'),
                  consul_ports_http | default('8500'),
                  consul_ports_rpc | default('8400'),
                  consul_ports_serf_lan | default('8301'),
                  consul_ports_serf_wan | default('8302'),
                  consul_ports_server | default('8300')
                ] if dcs_type == 'consul' else []),
              'cidr_ip': vpc_subnet_info.subnets[0].cidr_block
            }]
          }}
      register: ec2_security_group_result
      when: firewall | bool

    # S3 bucket
    - name: "AWS: Create S3 bucket '{{ aws_s3_bucket_name }}'"
      amazon.aws.s3_bucket:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ aws_s3_bucket_name }}"
        region: "{{ aws_s3_bucket_region }}"
        state: present
        object_lock_enabled: "{{ aws_s3_bucket_object_lock_enabled }}"
        encryption: "{{ aws_s3_bucket_encryption }}"
        public_access:
          block_public_acls: true
          ignore_public_acls: true
      when:
        - (pgbackrest_install | bool or wal_g_install | bool)
        - aws_s3_bucket_create | bool

    # Server and volume
    - name: "AWS: Create or modify EC2 instance"
      amazon.aws.ec2_instance:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
        state: present
        instance_type: "{{ server_type }}"
        image_id: "{{ server_image }}"
        key_name: "{{ ssh_key_name }}"
        region: "{{ server_location }}"
        security_groups: "{{ ([] if not firewall | bool else [patroni_cluster_name + '-security-group']) }}"
        vpc_subnet_id: "{{ server_network }}"
        network:
          assign_public_ip: true
          delete_on_termination: true
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_type: "{{ volume_type | default('gp3', true) }}"
              volume_size: "{{ system_volume_size | int }}"
              delete_on_termination: true
          - device_name: /dev/sdb
            ebs:
              volume_type: "{{ volume_type | default('gp3', true) }}"
              volume_size: "{{ volume_size | int }}"
              delete_on_termination: true
      loop: "{{ range(0, servers_count | int) | list }}"
      loop_control:
        index_var: idx
        label: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
      register: server_result
      until:
        - server_result.instances[0].public_ip_address is defined
        - server_result.instances[0].public_ip_address | length > 0
      retries: 3
      delay: 10
      when: not aws_ec2_spot_instance | default(false) | bool

    # Spot instance (if 'aws_ec2_spot_instance' is 'true')
    - block:
        - name: "AWS: Gather information about EC2 Spot instances"
          amazon.aws.ec2_instance_info:
            access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
            secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
            region: "{{ server_location }}"
            filters:
              instance-lifecycle: "spot"
              instance-type: "{{ server_type }}"
              image-id: "{{ server_image }}"
              instance-state-name: ["pending", "running", "shutting-down", "stopping", "stopped"]
              "tag:Name": "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
          loop: "{{ range(0, servers_count | int) | list }}"
          loop_control:
            index_var: idx
            label: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
          register: ec2_instance_info

        # if spot instances are still created, create them
        - name: "AWS: Create a request for EC2 Spot instance"
          amazon.aws.ec2_spot_instance:
            access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
            secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
            region: "{{ server_location }}"
            state: present
            launch_specification:
              instance_type: "{{ server_type }}"
              image_id: "{{ server_image }}"
              key_name: "{{ ssh_key_name }}"
              network_interfaces:
                - subnet_id: "{{ server_network }}"
                  groups: "{{ ec2_security_group_result.group_id }}"
                  associate_public_ip_address: true
                  delete_on_termination: true
                  device_index: 0
              block_device_mappings:
                - device_name: /dev/sda1
                  ebs:
                    volume_type: "{{ volume_type | default('gp3', true) }}"
                    volume_size: 100 # TODO: use 'system_volume_size' variable (https://github.com/ansible-collections/amazon.aws/issues/1949)
                    delete_on_termination: true
                - device_name: /dev/sdb
                  ebs:
                    volume_type: "{{ volume_type | default('gp3', true) }}"
                    volume_size: 100 # TODO: use 'volume_size' variable (https://github.com/ansible-collections/amazon.aws/issues/1949)
                    delete_on_termination: true
            tags:
              Name: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
          loop: "{{ ec2_instance_info.results }}"
          loop_control:
            index_var: idx
            label: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
          register: ec2_spot_instance_result
          when: item.instances[0] | default('') | length < 1

        - name: "AWS: Rename the EC2 Spot instance"
          amazon.aws.ec2_instance:
            access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
            secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
            region: "{{ server_location }}"
            name: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
            filters:
              spot-instance-request-id: "{{ item.spot_request.spot_instance_request_id }}"
          loop: "{{ ec2_spot_instance_result.results }}"
          loop_control:
            index_var: idx
            label: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
          register: server_result
          until:
            - server_result.instances[0].public_ip_address is defined
            - server_result.instances[0].public_ip_address | length > 0
          retries: 3
          delay: 10
          when: item.spot_request.spot_instance_request_id is defined

        # if spot instances have already been created, use them
        - name: "Set variable: server_result"
          ansible.builtin.set_fact:
            server_result: "{{ ec2_instance_info }}"
          when: not server_result.changed
      when: aws_ec2_spot_instance | default(false) | bool
  when: state == 'present'

- name: Wait for EC2 instance to be available via SSH
  ansible.builtin.wait_for:
    host: "{{ item.instances[0].public_ip_address }}"
    port: 22
    delay: 5
    timeout: 300
  loop: "{{ server_result.results }}"
  loop_control:
    label: "{{ item.instances[0].public_ip_address | default('N/A') }}"
  when:
    - server_result.results is defined
    - item.instances is defined

# Info
- name: Show EC2 instance info
  ansible.builtin.debug:
    msg:
      - "ID: {{ item.instances[0].instance_id }}"
      - "Name: {{ item.instances[0].tags.Name }}"
      - "Image: {{ item.instances[0].image_id }}"
      - "Type: {{ item.instances[0].instance_type }}"
      - "Volume Size: {{ volume_size }} GB"
      - "Public IP: {{ item.instances[0].public_ip_address }}"
      - "Private IP: {{ item.instances[0].private_ip_address }}"
  loop: "{{ server_result.results }}"
  loop_control:
    label: "{{ item.instances[0].public_ip_address | default('N/A') }}"
  when:
    - server_result.results is defined
    - item.instances is defined

# Inventory
- block:
    - name: "Inventory | Initialize ip_addresses variable"
      ansible.builtin.set_fact:
        ip_addresses: []

    - name: "Inventory | Extract IP addresses"
      ansible.builtin.set_fact:
        ip_addresses: >-
          {{ ip_addresses +
            [{'public_ip': item.instances[0].public_ip_address,
              'private_ip': item.instances[0].private_ip_address}]
          }}
      loop: "{{ server_result.results | selectattr('instances', 'defined') }}"
      loop_control:
        label: "public_ip: {{ item.instances[0].public_ip_address }}, private_ip: {{ item.instances[0].private_ip_address }}"

    - name: "Inventory | Generate in-memory inventory"
      ansible.builtin.import_tasks: inventory.yml
  when:
    - server_result.results is defined
    - server_result.results | selectattr('instances', 'defined')

# Delete the temporary ssh key from the cloud after creating the EC2 instance
- name: "AWS: Remove temporary SSH key '{{ ssh_key_name }}' from cloud"
  amazon.aws.ec2_key:
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
    name: "{{ ssh_key_name }}"
    region: "{{ server_location }}"
    state: absent
  register: ssh_key_result
  when:
    - ssh_key_name is defined
    - tmp_ssh_key_name is defined
    - ssh_key_name == tmp_ssh_key_name

# Delete (if state is absent)
- block:
    - name: "AWS: Delete EC2 instance"
      amazon.aws.ec2_instance:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"
        region: "{{ server_location }}"
        state: absent
      loop: "{{ range(0, servers_count | int) | list }}"
      loop_control:
        index_var: idx
        label: "{{ server_name | lower }}{{ '%02d' % (idx + 1) }}"

    - name: "AWS: Delete Security Group"
      amazon.aws.ec2_security_group:
        name: "{{ patroni_cluster_name }}-security-group"
        region: "{{ server_location }}"
        state: absent

    - name: "AWS: Delete S3 bucket '{{ patroni_cluster_name }}'"
      amazon.aws.s3_bucket:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ aws_s3_bucket_name }}"
        region: "{{ aws_s3_bucket_region }}"
        state: absent
        force: true
      when:
        - (pgbackrest_install | bool or wal_g_install | bool)
        - aws_s3_bucket_absent | default(false) | bool
  when: state == 'absent'

...
