---

- name: "Inventory | Add host to 'postgres_cluster', 'master' groups"
  ansible.builtin.add_host:
    name: "{{ item.private_ip }}"
    groups:
      - postgres_cluster
      - master
    ansible_ssh_host: "{{ item.public_ip }}"
  loop: "{{ [ip_addresses[0]] }}" # add the first item in the list
  loop_control:
    label: "{{ item.public_ip }}"
  changed_when: false

- name: "Inventory | Add host to 'postgres_cluster', 'replica' groups"
  ansible.builtin.add_host:
    name: "{{ item.private_ip }}"
    groups:
      - postgres_cluster
      - replica
    ansible_ssh_host: "{{ item.public_ip }}"
  loop: "{{ ip_addresses[1:] }}" # start with the 2nd item of the list
  loop_control:
    label: "{{ item.public_ip }}"
  when: ip_addresses | length > 1 # only if there is more than one item
  changed_when: false

- name: "Inventory | Add host to 'balancers' group"
  ansible.builtin.add_host:
    name: "{{ item.private_ip }}"
    group: balancers
    ansible_ssh_host: "{{ item.public_ip }}"
  loop: "{{ ip_addresses }}"
  loop_control:
    label: "{{ item.public_ip }}"
  changed_when: false
  when: with_haproxy_load_balancing | bool

- name: "Inventory | Add host to 'etcd_cluster' group"
  ansible.builtin.add_host:
    name: "{{ item.private_ip }}"
    group: etcd_cluster
    ansible_ssh_host: "{{ item.public_ip }}"
  loop: "{{ ip_addresses[:7] }}" # no more than 7 servers for the etcd cluster
  loop_control:
    label: "{{ item.public_ip }}"
  changed_when: false
  when: not dcs_exists | bool and dcs_type == "etcd"

- name: "Inventory | Add host to 'consul_instances' group"
  ansible.builtin.add_host:
    name: "{{ item.private_ip }}"
    group: consul_instances
    ansible_ssh_host: "{{ item.public_ip }}"
    consul_node_role: "{{ not dcs_exists | ternary('server', 'client') }}"
    consul_bootstrap_expect: true
    consul_datacenter: "{{ server_location }}"
  loop: "{{ ip_addresses }}"
  loop_control:
    label: "{{ item.public_ip }}"
  changed_when: false
  when: dcs_type == "consul"

...
